<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Sign In</name>
   <tag></tag>
   <elementGuidId>6d274061-7373-40d3-84e9-aed34825ee31</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@data-automation-id = 'click_filter']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@data-automation-id = 'click_filter']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[data-automation-id=&quot;click_filter&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Sign In&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>1862600f-136e-44a3-a6e4-d386a3110339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>font-size</name>
      <type>Main</type>
      <value>14</value>
      <webElementGuid>7720cdf4-3c44-4a18-aca7-b8f01b9d33a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>32584830-9cfb-43a0-807d-b0438ec33c11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Sign In</value>
      <webElementGuid>1d6a4901-c74e-4abf-a86a-75f07ec24db0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>1dfae66d-d752-438c-98b7-c76bbfb6752e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>06205b98-5263-4da3-8ac8-a77b803378ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-automation-id</name>
      <type>Main</type>
      <value>click_filter</value>
      <webElementGuid>3c7627fe-cf49-43f1-a6c0-06ee323a8ca2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>css-z8rqje</value>
      <webElementGuid>010b243d-c049-4ab3-8ad7-c3b846096daa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a585d17b5b9a2bd5c7e6c2f6501388ff</value>
      <webElementGuid>49c3e7ac-916c-404a-b4cb-dee031657c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@data-automation-id = 'click_filter']</value>
      <webElementGuid>6f30ac13-22cb-43da-bd94-a99df78afd59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-automation-id = 'click_filter']</value>
      <webElementGuid>3537598b-1bbe-422a-8370-3c7c6eef98d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
